import unittest
from pathlib import Path, PurePosixPath
import subprocess
import tempfile

from kb_repo import excluded_pattern, generated_reason, linguist_generated, repomix_candidates, skip_reason, tracked_files


class ContentFilterTest(unittest.TestCase):
    def test_repomix_mechanical_selection_is_applied_to_tracked_files(self):
        with tempfile.TemporaryDirectory() as temp:
            repo = Path(temp)
            subprocess.run(["git", "init", "-q", str(repo)], check=True)
            for name, body in {
                "app.py": "print('useful')\n",
                "dist/generated.js": "const generated = true;\n",
                "noise.txt": "unneeded\n",
                ".repomixignore": "noise.txt\n",
            }.items():
                path = repo / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(body)
            subprocess.run(["git", "-C", str(repo), "add", "-f", "."], check=True)
            (repo / "untracked.py").write_text("print('untracked')\n")

            selected = repomix_candidates(repo) & set(tracked_files(repo))

        self.assertIn(PurePosixPath("app.py"), selected)
        self.assertNotIn(PurePosixPath("dist/generated.js"), selected)
        self.assertNotIn(PurePosixPath("noise.txt"), selected)
        self.assertNotIn(PurePosixPath("untracked.py"), selected)

    def test_user_exclude_patterns_match_prefixes_and_globs(self):
        patterns = ["tests", "ui/", "*/_next/*", "docs/*.md"]
        def hit(path):
            return excluded_pattern(PurePosixPath(path), patterns)
        self.assertEqual(hit("tests/unit/test_a.py"), "tests")
        self.assertEqual(hit("tests"), "tests")
        self.assertIsNone(hit("tests_helper.py"))  # prefix is a whole path segment
        self.assertEqual(hit("ui/litellm-dashboard/app.tsx"), "ui/")
        self.assertEqual(hit("litellm/proxy/_experimental/out/_next/static/chunks/a.js"), "*/_next/*")
        self.assertEqual(hit("docs/guide.md"), "docs/*.md")
        self.assertIsNone(hit("litellm/main.py"))
        self.assertIsNone(excluded_pattern(PurePosixPath("a.py"), ["", " "]))

    def generated(self, path, text="x = 1\n", repo=None):
        return generated_reason(PurePosixPath(path), text.encode(), repo)

    def test_generated_detection_uses_objective_signals_only(self):
        # codegen suffixes and tool-output directories
        self.assertEqual(self.generated("api/v1/service_pb2.py"), "generated source")
        self.assertEqual(self.generated("web/vendor.min.js"), "generated source")
        self.assertEqual(self.generated("tests/__snapshots__/app.test.ts.snap"), "generated source")
        self.assertEqual(self.generated("out/_next/static/chunks/main.js"), "generated build output")
        self.assertEqual(self.generated("src/__generated__/schema.ts"), "generated build output")
        # header markers within the first lines
        self.assertEqual(self.generated("a.py", "# Code generated by protoc. DO NOT EDIT.\n"), "generated (header marker)")
        self.assertEqual(self.generated("a.ts", "/**\n * @generated SignedSource<<x>>\n */\n"), "generated (header marker)")
        self.assertEqual(self.generated("a.py", "# This file was automatically generated by Alembic\n"), "generated (header marker)")
        # the same words deep inside a file do not count
        body = "x = 1\n" * 20 + "# DO NOT EDIT this value by hand\n"
        self.assertIsNone(self.generated("a.py", body))
        # minified web assets, but not ordinary ones
        self.assertEqual(self.generated("static/app.js", "var a=1;" * 200 + "\n"), "minified/bundled asset")
        self.assertIsNone(self.generated("static/app.js", "var a = 1;\n" * 200))
        self.assertIsNone(self.generated("static/app.py", "x=" + "1" * 500 + "\n"))  # python never minified
        # hand-written code and tests stay in
        self.assertIsNone(self.generated("litellm/proxy/utils.py", "import os\n\n\ndef f():\n    return 1\n"))
        self.assertIsNone(self.generated("tests/unit/test_router.py", "def test_x():\n    assert 1\n"))
        self.assertIsNone(self.generated("ui/dashboard/page.tsx", "export default function Page() {}\n"))

    def test_next_export_pages_beside_a_next_tree_and_linguist_attribute(self):
        with tempfile.TemporaryDirectory() as temp:
            repo = Path(temp)
            subprocess.run(["git", "init", "-q", str(repo)], check=True)
            for name, body in {
                "app/out/_next/static/x.js": "var a=1;\n",
                "app/out/index.html": "<html>\n<body>hi</body>\n</html>\n",
                "app/src/page.tsx": "export const a = 1;\n",
                "schema.graphql.ts": "export const s = 1;\n",
                ".gitattributes": "schema.graphql.ts linguist-generated=true\n",
            }.items():
                path = repo / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(body)
            subprocess.run(["git", "-C", str(repo), "add", "-f", "."], check=True)
            self.assertEqual(self.generated("app/out/index.html", repo=repo), "generated build output")
            self.assertIsNone(self.generated("app/src/page.tsx", repo=repo))
            marked = linguist_generated(repo, tracked_files(repo))
            self.assertEqual(marked, {PurePosixPath("schema.graphql.ts")})
            self.assertEqual(skip_reason(PurePosixPath("schema.graphql.ts"), b"export const s = 1;\n", 600_000,
                                         generated_paths=marked), "generated (linguist-generated attribute)")

    def reason(self, path, size):
        return skip_reason(PurePosixPath(path), b"x" * size, 600_000)

    def test_excludes_lottie_json(self):
        self.assertEqual(
            self.reason("web/assets/json/lottie/animation.json", 1_000),
            "data-driven visual asset",
        )

    def test_excludes_large_recorded_test_data(self):
        self.assertEqual(
            self.reason("spec/cassettes/payment/success.yml", 100_000),
            "large test fixture/cassette/snapshot",
        )
        self.assertEqual(
            self.reason("db/fixtures/products.csv", 150_000),
            "large test fixture/cassette/snapshot",
        )

    def test_excludes_large_static_web_assets(self):
        self.assertEqual(
            self.reason("app/assets/javascripts/vendor-library.js", 150_000),
            "large static/generated web asset",
        )
        self.assertEqual(
            self.reason("static/developers/openapi.html", 150_000),
            "large static/generated web asset",
        )

    def test_excludes_generated_api_bundle(self):
        self.assertEqual(
            self.reason("openapi/bundled.yaml", 10_000),
            "generated/bundled API description",
        )

    def test_excludes_large_structured_data(self):
        self.assertEqual(
            self.reason("config/settings/prices.json", 200_000),
            "large structured data/snapshot",
        )

    def test_keeps_small_configuration_and_handwritten_api_source(self):
        self.assertIsNone(self.reason("config/settings/prices.json", 20_000))
        self.assertIsNone(self.reason("openapi/source.yaml", 50_000))

    def test_keeps_large_source_and_design_documents(self):
        self.assertIsNone(self.reason("app/services/large_service.rb", 300_000))
        self.assertIsNone(self.reason("docs/design/architecture.md", 300_000))


if __name__ == "__main__":
    unittest.main()
